### ISSUE TITLE
Builders let anti-nuke ramparts decay after nuke lands

### ISSUE THREAD

**Issue by DragonFire12** [jordansafer/screeps#51]
I've seen the way you defend the base,but I have to say,it's not the most efficient because of all the walls,i know they are easier to maintain than ramparts but walls don't allow creeps to be in them,so defenses aren't going to be that effective,meaning you can only use ranged defenders,also enemy creeps can position themselves in front of the ramparts so your creeps can't get out,i suggest making all the walls into ramparts so that allows for more defensive options and overall more travel options when it comes to creep movement.

**Comment by jordansafer** [comment]
+1

**Comment by DragonFire12** [comment]
+1?:)

**Comment by JonathanSafer** [comment]
The problem with ramparts is that they cost energy to maintain. Walls take energy to build up once, but they don't fall down, so they are a sunk cost. If anybody attacks us and our ranged defenders (in the works) combined with towers can't hold them off, we simply can't keep the room. We are better taking the economic hit of losing some rooms due to this minor defensive flaw than taking the economic hit of permanently maintaining ramparts across the empire.

**Comment by jordansafer** [comment]
circling back to this, bases now spawn boosted ranged attackers that stay in the base and defend, 3 of these together are able to defeat a trio (2 healers 1 breaker), untested against quads bc we aren’t attacked by quads. cost of a lost base is massive (2 cpu * 3 weeks to replace) but we haven’t lost a base. question is, what is the cost of maintaining ramparts?

**Comment by JonathanSafer** [comment]
~50 ramparts per room, decaying at 300 hits per 100 ticks each. Thats 3000 hits per 1k ticks or 2 intents per 1k ticks for our current builder. multiplied by 50 ramparts, we get 100 intents or 20 cpu per 1k ticks per room. With 14 rooms atm, that translates to 280 cpu per 1k ticks or .28 cpu per tick.

**Comment by JonathanSafer** [comment]
ofc the above calc did not take into account the cpu cost of motion for the builder, as well as energy costs for both the builder and the repair ops. That should all be comparatively little though. I would say 0.28 is certainly not acceptable, especially since it will only rise over the course of our expansion. 0.28 cpu can run a 4 creep military operation with 15 - 20% uptime, which we would probably never achieve (uptime-wise), and would be necessary to remove any enemy that is strong enough to threaten us.

**Comment by JonathanSafer** [comment]
In the spirit of getting something useful out of this issue, I would say that this has highlighted the importance of only maintaining ramparts that are absolutely necessary.

This means that builders will have to be able to ignore ramparts that were created for nuke defense, but are no longer needed.

**Comment by JonathanSafer** [comment]
builders can judge whether a rampart is a 'nuke rampart' vs regular by looking at the structure underneath. If the structure underneath is a core structure (or maybe we'll provide a list of valid structures in settings), the rampart should only be maintained up to the value of the total damage to be dealt by all incoming nukes.

**Comment by jordansafer** [comment]
I think the other big part of this is autoplacement of rampart construction sites when a nuke is launched
